/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "fluent-integrations"
include(":fluentqa-logistics")
include(":qabox-vika")
include(":qabox-openai")
include(":qabox-feishu")

