/*
 * This file was generated by the Gradle 'init' task.
 */
plugins{
    java
}

dependencies {
    implementation("org.projectlombok:lombok:1.18.26")
    implementation("cn.hutool:hutool-all:5.8.12")
    implementation("com.alibaba.fastjson2:fastjson2:2.0.16")
    implementation("com.alibaba:fastjson:2.0.16")
}

description = "fluentqa-logistics"
