/*
 * This file was generated by the Gradle 'init' task.
 */

plugins{
    java
}

dependencies {
    implementation("org.projectlombok:lombok:1.18.26")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.14.2")
    implementation("com.squareup.okhttp3:okhttp:4.10.0")
    implementation("com.squareup.retrofit2:retrofit:2.9.0")
    implementation("com.squareup.retrofit2:adapter-rxjava2:2.9.0")
    implementation("com.squareup.retrofit2:converter-jackson:2.9.0")
}

description = "qabox-openai"
